// Auto-generated by analyze_env.py

#ifndef NTINT_ENV_PROFILES_H
#define NTINT_ENV_PROFILES_H
#include "../include/DirectMod.h"

static const NTintEnvironment NT_DARK_PRESET0 = {
    { 0.366288f, 0.313702f, 0.247380f },
    0.316387f,
    0.076761f,
    0.081498f
};

static const NTintEnvironment NT_DARK_PRESET1 = {
    { 0.407750f, 0.380243f, 0.332063f },
    0.381830f,
    0.160679f,
    0.077247f
};

static const NTintEnvironment NT_DARK_PRESET2 = {
    { 0.066031f, 0.069759f, 0.065071f },
    0.066981f,
    0.038833f,
    0.008249f
};

static const NTintEnvironment NT_DARK_PRESET3 = {
    { 0.155185f, 0.124283f, 0.056905f },
    0.126798f,
    0.185600f,
    0.079320f
};

static const NTintEnvironment NT_DARK_PRESET4 = {
    { 0.328310f, 0.227350f, 0.034276f },
    0.233694f,
    0.078093f,
    0.219701f
};

static const NTintEnvironment NT_DARK_PRESET5 = {
    { 0.364166f, 0.285605f, 0.120616f },
    0.292182f,
    0.043767f,
    0.194664f
};

static const NTintEnvironment NT_DARK_COM = {
    { 0.281288f, 0.233490f, 0.142719f },
    0.236312f,
    0.097289f,
    0.110113f
};

#endif // NTINT_ENV_PROFILES_H
